name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

     - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/LLM-Analyst:$GITHUB_SHA .

      - name: Test Docker Container
        run: |
          docker run -d -p 8501:8501 --name LLM-Analyst \
            ${{ secrets.DOCKERHUB_USERNAME }}/LLM-Analyst:$GITHUB_SHA

          sleep 10
          
          if docker ps --filter "name=LLM-Analyst" --filter "status=running" | grep LLM-Analyst; then
            echo "✅ Container started successfully!"
            docker stop LLM-Analyst
            docker rm LLM-Analyst
          else
            echo "❌ Container failed to start. Fetching logs..."
            docker logs LLM-Analyst || echo "⚠️ No logs available"
            exit 1
          fi
